# Generated by Django 4.2.17 on 2025-01-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriMaxApp', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=255)),
                ('farm_location', models.CharField(max_length=255)),
            ],
        ),
    ]
