# Generated by Django 4.2.17 on 2025-01-23 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgriMaxApp', '0003_farminformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='farminformation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
    ]
